'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ProxyWsGetArchivos
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ProcWsGetArchivosProcesoSoapBinding", [Namespace]:="KbComprasPortal")>  _
    Partial Public Class ProcWsGetArchivosProceso
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ExecuteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CteValidacionMasiva.My.MySettings.Default.CteValidacionMasiva_ProxyWsGetArchivos_ProcWsGetArchivosProceso
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ExecuteCompleted As ExecuteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("KbComprasPortalaction/APROCWSGETARCHIVOSPROCESO.Execute", RequestElementName:="ProcWsGetArchivosProceso.Execute", RequestNamespace:="KbComprasPortal", ResponseElementName:="ProcWsGetArchivosProceso.ExecuteResponse", ResponseNamespace:="KbComprasPortal", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Execute() As <System.Xml.Serialization.XmlArrayAttribute("Sdtcmarchivo"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> SDTCMArchivoSDTCMArchivoItem()
            Dim results() As Object = Me.Invoke("Execute", New Object(-1) {})
            Return CType(results(0),SDTCMArchivoSDTCMArchivoItem())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExecuteAsync()
            Me.ExecuteAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExecuteAsync(ByVal userState As Object)
            If (Me.ExecuteOperationCompleted Is Nothing) Then
                Me.ExecuteOperationCompleted = AddressOf Me.OnExecuteOperationCompleted
            End If
            Me.InvokeAsync("Execute", New Object(-1) {}, Me.ExecuteOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecuteOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExecuteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExecuteCompleted(Me, New ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="SDTCMArchivo.SDTCMArchivoItem", [Namespace]:="KbComprasPortal")>  _
    Partial Public Class SDTCMArchivoSDTCMArchivoItem
        
        Private cMArchivoIdField As Long
        
        Private cMArchivoFechaField As System.Nullable(Of Date)
        
        Private cMArchivoUsuarioField As String
        
        Private cMArchivoTFacturasField As Long
        
        Private cMArchivoStatusField As Short
        
        '''<comentarios/>
        Public Property CMArchivoId() As Long
            Get
                Return Me.cMArchivoIdField
            End Get
            Set
                Me.cMArchivoIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CMArchivoFecha() As System.Nullable(Of Date)
            Get
                Return Me.cMArchivoFechaField
            End Get
            Set
                Me.cMArchivoFechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CMArchivoUsuario() As String
            Get
                Return Me.cMArchivoUsuarioField
            End Get
            Set
                Me.cMArchivoUsuarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CMArchivoTFacturas() As Long
            Get
                Return Me.cMArchivoTFacturasField
            End Get
            Set
                Me.cMArchivoTFacturasField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CMArchivoStatus() As Short
            Get
                Return Me.cMArchivoStatusField
            End Get
            Set
                Me.cMArchivoStatusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")>  _
    Public Delegate Sub ExecuteCompletedEventHandler(ByVal sender As Object, ByVal e As ExecuteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExecuteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SDTCMArchivoSDTCMArchivoItem()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SDTCMArchivoSDTCMArchivoItem())
            End Get
        End Property
    End Class
End Namespace
